apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandstore-hyperconverged-test-runner
  labels:
    app: sandstore-hyperconverged
    app.kubernetes.io/name: sandstore-hyperconverged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandstore-hyperconverged-test-runner
  labels:
    app: sandstore-hyperconverged
    app.kubernetes.io/name: sandstore-hyperconverged
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["statefulsets/scale"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandstore-hyperconverged-test-runner
  labels:
    app: sandstore-hyperconverged
    app.kubernetes.io/name: sandstore-hyperconverged
subjects:
  - kind: ServiceAccount
    name: sandstore-hyperconverged-test-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sandstore-hyperconverged-test-runner
