apiVersion: v1
kind: Service
metadata:
  name: sandstore-hyperconverged-nodeport
  labels:
    app: sandstore-hyperconverged
    app.kubernetes.io/name: sandstore-hyperconverged
spec:
  type: NodePort
  selector:
    app: sandstore-hyperconverged
    sandstore-role: node
  ports:
    - name: client
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
