apiVersion: v1
kind: Service
metadata:
  name: sandstore-hyperconverged-headless
  labels:
    app: sandstore-hyperconverged
    app.kubernetes.io/name: sandstore-hyperconverged
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: sandstore-hyperconverged
    sandstore-role: node
  ports:
    - name: raft
      port: 8080
      targetPort: 8080
      protocol: TCP
